
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "88abf76a49b9aaad5f4a3084e1cff9a62c50f0d6",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
