
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f10b298e49b1531fb599c9e4f4bb50745b1a5565",
 "version": "2.10.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
