# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Feb 22 23:03:54 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(373, 778)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton_calculate = QtGui.QPushButton(self.centralwidget)
        self.pushButton_calculate.setGeometry(QtCore.QRect(20, 640, 131, 27))
        self.pushButton_calculate.setObjectName(_fromUtf8("pushButton_calculate"))
        self.label_info = QtGui.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(20, 700, 331, 20))
        self.label_info.setObjectName(_fromUtf8("label_info"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(200, 650, 151, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(20, 10, 341, 611))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 341, 394))
        self.page.setObjectName(_fromUtf8("page"))
        self.layoutWidget = QtGui.QWidget(self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 291, 331))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_loadRFEMxls = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_loadRFEMxls.setObjectName(_fromUtf8("pushButton_loadRFEMxls"))
        self.verticalLayout.addWidget(self.pushButton_loadRFEMxls)
        self.pushButton_loadROBOTcsv = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_loadROBOTcsv.setEnabled(True)
        self.pushButton_loadROBOTcsv.setObjectName(_fromUtf8("pushButton_loadROBOTcsv"))
        self.verticalLayout.addWidget(self.pushButton_loadROBOTcsv)
        self.pushButton_loadAlgor = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_loadAlgor.setEnabled(False)
        self.pushButton_loadAlgor.setObjectName(_fromUtf8("pushButton_loadAlgor"))
        self.verticalLayout.addWidget(self.pushButton_loadAlgor)
        self.textBrowser_loaddata = QtGui.QTextBrowser(self.layoutWidget)
        self.textBrowser_loaddata.setObjectName(_fromUtf8("textBrowser_loaddata"))
        self.verticalLayout.addWidget(self.textBrowser_loaddata)
        self.pushButton_clearData = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_clearData.setObjectName(_fromUtf8("pushButton_clearData"))
        self.verticalLayout.addWidget(self.pushButton_clearData)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 341, 394))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.layoutWidget1 = QtGui.QWidget(self.page_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 20, 291, 155))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_plot3D = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_plot3D.setEnabled(True)
        self.pushButton_plot3D.setObjectName(_fromUtf8("pushButton_plot3D"))
        self.verticalLayout_4.addWidget(self.pushButton_plot3D)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboBox_SelectViewPoint = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_SelectViewPoint.setObjectName(_fromUtf8("comboBox_SelectViewPoint"))
        self.horizontalLayout.addWidget(self.comboBox_SelectViewPoint)
        self.pushButton_AutoSet = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_AutoSet.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_AutoSet.setObjectName(_fromUtf8("pushButton_AutoSet"))
        self.horizontalLayout.addWidget(self.pushButton_AutoSet)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.pushButton_PlotPreview = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_PlotPreview.setObjectName(_fromUtf8("pushButton_PlotPreview"))
        self.verticalLayout_2.addWidget(self.pushButton_PlotPreview)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.pushButton_plotThickness = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_plotThickness.setEnabled(True)
        self.pushButton_plotThickness.setObjectName(_fromUtf8("pushButton_plotThickness"))
        self.verticalLayout_4.addWidget(self.pushButton_plotThickness)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 341, 394))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.pushButton_Apllytopanel = QtGui.QPushButton(self.page_2)
        self.pushButton_Apllytopanel.setGeometry(QtCore.QRect(20, 210, 291, 27))
        self.pushButton_Apllytopanel.setObjectName(_fromUtf8("pushButton_Apllytopanel"))
        self.textBrowser_panelprop = QtGui.QTextBrowser(self.page_2)
        self.textBrowser_panelprop.setEnabled(True)
        self.textBrowser_panelprop.setGeometry(QtCore.QRect(20, 250, 291, 131))
        self.textBrowser_panelprop.setObjectName(_fromUtf8("textBrowser_panelprop"))
        self.label_3 = QtGui.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(30, 39, 101, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.page_2)
        self.label_6.setGeometry(QtCore.QRect(28, 69, 101, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(70, 100, 66, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(70, 140, 69, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(30, 170, 111, 31))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.comboBox_concreteclass = QtGui.QComboBox(self.page_2)
        self.comboBox_concreteclass.setGeometry(QtCore.QRect(151, 36, 161, 27))
        self.comboBox_concreteclass.setObjectName(_fromUtf8("comboBox_concreteclass"))
        self.comboBox_steelclass = QtGui.QComboBox(self.page_2)
        self.comboBox_steelclass.setGeometry(QtCore.QRect(151, 69, 161, 27))
        self.comboBox_steelclass.setObjectName(_fromUtf8("comboBox_steelclass"))
        self.label_4 = QtGui.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(170, 10, 38, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(260, 10, 37, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBox_dp = QtGui.QComboBox(self.page_2)
        self.comboBox_dp.setGeometry(QtCore.QRect(152, 103, 78, 27))
        self.comboBox_dp.setObjectName(_fromUtf8("comboBox_dp"))
        self.comboBox_dn = QtGui.QComboBox(self.page_2)
        self.comboBox_dn.setGeometry(QtCore.QRect(236, 103, 78, 27))
        self.comboBox_dn.setObjectName(_fromUtf8("comboBox_dn"))
        self.lineEdit_ap = QtGui.QLineEdit(self.page_2)
        self.lineEdit_ap.setGeometry(QtCore.QRect(152, 138, 78, 27))
        self.lineEdit_ap.setObjectName(_fromUtf8("lineEdit_ap"))
        self.lineEdit_an = QtGui.QLineEdit(self.page_2)
        self.lineEdit_an.setGeometry(QtCore.QRect(236, 138, 78, 27))
        self.lineEdit_an.setObjectName(_fromUtf8("lineEdit_an"))
        self.comboBox_cracklimp = QtGui.QComboBox(self.page_2)
        self.comboBox_cracklimp.setGeometry(QtCore.QRect(152, 173, 78, 27))
        self.comboBox_cracklimp.setObjectName(_fromUtf8("comboBox_cracklimp"))
        self.comboBox_cracklimn = QtGui.QComboBox(self.page_2)
        self.comboBox_cracklimn.setGeometry(QtCore.QRect(236, 173, 78, 27))
        self.comboBox_cracklimn.setObjectName(_fromUtf8("comboBox_cracklimn"))
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 341, 394))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.layoutWidget2 = QtGui.QWidget(self.page_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 10, 291, 335))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_plot_nx = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_plot_nx.setObjectName(_fromUtf8("pushButton_plot_nx"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_nx)
        self.pushButton_plot_ny = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_plot_ny.setObjectName(_fromUtf8("pushButton_plot_ny"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_ny)
        self.pushButton_plot_nxy = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_plot_nxy.setObjectName(_fromUtf8("pushButton_plot_nxy"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_nxy)
        self.pushButton_plot_mx = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_plot_mx.setObjectName(_fromUtf8("pushButton_plot_mx"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_mx)
        self.pushButton_plot_my = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_plot_my.setObjectName(_fromUtf8("pushButton_plot_my"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_my)
        self.pushButton_plot_mxy = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_plot_mxy.setObjectName(_fromUtf8("pushButton_plot_mxy"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_mxy)
        self.line = QtGui.QFrame(self.layoutWidget2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.pushButton_plot_equNX = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_plot_equNX.setObjectName(_fromUtf8("pushButton_plot_equNX"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_equNX)
        self.pushButton_plot_equNY = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_plot_equNY.setObjectName(_fromUtf8("pushButton_plot_equNY"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_equNY)
        self.pushButton_plot_equMX = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_plot_equMX.setObjectName(_fromUtf8("pushButton_plot_equMX"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_equMX)
        self.pushButton_plot_equMY = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_plot_equMY.setObjectName(_fromUtf8("pushButton_plot_equMY"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_equMY)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 341, 394))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.label_38 = QtGui.QLabel(self.page_5)
        self.label_38.setGeometry(QtCore.QRect(20, 60, 81, 21))
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.page_5)
        self.label_39.setGeometry(QtCore.QRect(17, 90, 81, 31))
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.line_4 = QtGui.QFrame(self.page_5)
        self.line_4.setGeometry(QtCore.QRect(111, 126, 178, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_10 = QtGui.QLabel(self.page_5)
        self.label_10.setGeometry(QtCore.QRect(130, 30, 57, 17))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.page_5)
        self.label_11.setGeometry(QtCore.QRect(210, 30, 71, 17))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.pushButton_plotApx = QtGui.QPushButton(self.page_5)
        self.pushButton_plotApx.setGeometry(QtCore.QRect(112, 57, 85, 27))
        self.pushButton_plotApx.setObjectName(_fromUtf8("pushButton_plotApx"))
        self.pushButton_plotApy = QtGui.QPushButton(self.page_5)
        self.pushButton_plotApy.setGeometry(QtCore.QRect(203, 57, 85, 27))
        self.pushButton_plotApy.setObjectName(_fromUtf8("pushButton_plotApy"))
        self.pushButton_plotAnx = QtGui.QPushButton(self.page_5)
        self.pushButton_plotAnx.setGeometry(QtCore.QRect(112, 92, 85, 27))
        self.pushButton_plotAnx.setObjectName(_fromUtf8("pushButton_plotAnx"))
        self.pushButton_plotAny = QtGui.QPushButton(self.page_5)
        self.pushButton_plotAny.setGeometry(QtCore.QRect(203, 92, 85, 27))
        self.pushButton_plotAny.setObjectName(_fromUtf8("pushButton_plotAny"))
        self.pushButton_plot_crackx = QtGui.QPushButton(self.page_5)
        self.pushButton_plot_crackx.setGeometry(QtCore.QRect(109, 150, 85, 27))
        self.pushButton_plot_crackx.setObjectName(_fromUtf8("pushButton_plot_crackx"))
        self.pushButton_plot_cracky = QtGui.QPushButton(self.page_5)
        self.pushButton_plot_cracky.setGeometry(QtCore.QRect(200, 150, 85, 27))
        self.pushButton_plot_cracky.setObjectName(_fromUtf8("pushButton_plot_cracky"))
        self.pushButton_plot_ksieffx = QtGui.QPushButton(self.page_5)
        self.pushButton_plot_ksieffx.setGeometry(QtCore.QRect(109, 185, 85, 27))
        self.pushButton_plot_ksieffx.setObjectName(_fromUtf8("pushButton_plot_ksieffx"))
        self.pushButton_plot_ksieffy = QtGui.QPushButton(self.page_5)
        self.pushButton_plot_ksieffy.setGeometry(QtCore.QRect(200, 185, 85, 27))
        self.pushButton_plot_ksieffy.setObjectName(_fromUtf8("pushButton_plot_ksieffy"))
        self.pushButton_plot_mimosx = QtGui.QPushButton(self.page_5)
        self.pushButton_plot_mimosx.setGeometry(QtCore.QRect(109, 220, 85, 27))
        self.pushButton_plot_mimosx.setObjectName(_fromUtf8("pushButton_plot_mimosx"))
        self.pushButton_plot_mimosy = QtGui.QPushButton(self.page_5)
        self.pushButton_plot_mimosy.setGeometry(QtCore.QRect(200, 220, 85, 27))
        self.pushButton_plot_mimosy.setObjectName(_fromUtf8("pushButton_plot_mimosy"))
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 341, 394))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.label_12 = QtGui.QLabel(self.page_6)
        self.label_12.setGeometry(QtCore.QRect(30, 10, 58, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.page_6)
        self.label_13.setGeometry(QtCore.QRect(240, 10, 58, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tableWidget_Apscale = QtGui.QTableWidget(self.page_6)
        self.tableWidget_Apscale.setGeometry(QtCore.QRect(10, 31, 81, 281))
        self.tableWidget_Apscale.setObjectName(_fromUtf8("tableWidget_Apscale"))
        self.tableWidget_Apscale.setColumnCount(0)
        self.tableWidget_Apscale.setRowCount(0)
        self.tableWidget_Anscale = QtGui.QTableWidget(self.page_6)
        self.tableWidget_Anscale.setGeometry(QtCore.QRect(220, 30, 81, 281))
        self.tableWidget_Anscale.setObjectName(_fromUtf8("tableWidget_Anscale"))
        self.tableWidget_Anscale.setColumnCount(0)
        self.tableWidget_Anscale.setRowCount(0)
        self.label_scaleUnit = QtGui.QLabel(self.page_6)
        self.label_scaleUnit.setGeometry(QtCore.QRect(107, 10, 91, 20))
        self.label_scaleUnit.setObjectName(_fromUtf8("label_scaleUnit"))
        self.label_scaleUnit_2 = QtGui.QLabel(self.page_6)
        self.label_scaleUnit_2.setGeometry(QtCore.QRect(100, 30, 111, 20))
        self.label_scaleUnit_2.setObjectName(_fromUtf8("label_scaleUnit_2"))
        self.layoutWidget3 = QtGui.QWidget(self.page_6)
        self.layoutWidget3.setGeometry(QtCore.QRect(110, 70, 101, 85))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_14 = QtGui.QLabel(self.layoutWidget3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_6.addWidget(self.label_14)
        self.pushButton_ApllyToScale = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_ApllyToScale.setObjectName(_fromUtf8("pushButton_ApllyToScale"))
        self.verticalLayout_6.addWidget(self.pushButton_ApllyToScale)
        self.pushButton_spaceing = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_spaceing.setObjectName(_fromUtf8("pushButton_spaceing"))
        self.verticalLayout_6.addWidget(self.pushButton_spaceing)
        self.layoutWidget4 = QtGui.QWidget(self.page_6)
        self.layoutWidget4.setGeometry(QtCore.QRect(110, 230, 101, 52))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_2 = QtGui.QLabel(self.layoutWidget4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.comboBox_presetAscale = QtGui.QComboBox(self.layoutWidget4)
        self.comboBox_presetAscale.setObjectName(_fromUtf8("comboBox_presetAscale"))
        self.verticalLayout_5.addWidget(self.comboBox_presetAscale)
        self.layoutWidget5 = QtGui.QWidget(self.page_6)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 320, 87, 62))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.pushButton_mapApx = QtGui.QPushButton(self.layoutWidget5)
        self.pushButton_mapApx.setObjectName(_fromUtf8("pushButton_mapApx"))
        self.verticalLayout_11.addWidget(self.pushButton_mapApx)
        self.pushButton_mapApy = QtGui.QPushButton(self.layoutWidget5)
        self.pushButton_mapApy.setObjectName(_fromUtf8("pushButton_mapApy"))
        self.verticalLayout_11.addWidget(self.pushButton_mapApy)
        self.layoutWidget6 = QtGui.QWidget(self.page_6)
        self.layoutWidget6.setGeometry(QtCore.QRect(220, 320, 87, 62))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.pushButton_mapAnx = QtGui.QPushButton(self.layoutWidget6)
        self.pushButton_mapAnx.setAutoFillBackground(False)
        self.pushButton_mapAnx.setObjectName(_fromUtf8("pushButton_mapAnx"))
        self.verticalLayout_12.addWidget(self.pushButton_mapAnx)
        self.pushButton_mapAny = QtGui.QPushButton(self.layoutWidget6)
        self.pushButton_mapAny.setObjectName(_fromUtf8("pushButton_mapAny"))
        self.verticalLayout_12.addWidget(self.pushButton_mapAny)
        self.toolBox.addItem(self.page_6, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 341, 394))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.toolBox.addItem(self.page_7, _fromUtf8(""))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(20, 680, 341, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 373, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_projekt = QtGui.QAction(MainWindow)
        self.actionSave_projekt.setEnabled(False)
        self.actionSave_projekt.setObjectName(_fromUtf8("actionSave_projekt"))
        self.actionOpen_projekt = QtGui.QAction(MainWindow)
        self.actionOpen_projekt.setObjectName(_fromUtf8("actionOpen_projekt"))

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "STRUTHON.CONCRETE.PANEL", None))
        self.pushButton_calculate.setText(_translate("MainWindow", "Calculate", None))
        self.label_info.setText(_translate("MainWindow", "StruthonConcretePanel ver.0.1 ( www.struthon.org)                                                                                   ", None))
        self.pushButton_loadRFEMxls.setText(_translate("MainWindow", "Load from RFEM Dlubal xls output file", None))
        self.pushButton_loadROBOTcsv.setText(_translate("MainWindow", "Load from Robot csv output file", None))
        self.pushButton_loadAlgor.setText(_translate("MainWindow", "Load from Algor", None))
        self.pushButton_clearData.setText(_translate("MainWindow", "Clear data", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", ">>> Load data", None))
        self.pushButton_plot3D.setText(_translate("MainWindow", "Show 3d geometry", None))
        self.label.setText(_translate("MainWindow", "Select view point for plots", None))
        self.pushButton_AutoSet.setText(_translate("MainWindow", "Auto set", None))
        self.pushButton_PlotPreview.setText(_translate("MainWindow", "Plot preview", None))
        self.pushButton_plotThickness.setText(_translate("MainWindow", "Panel thickness plot", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", ">>> Geometry and view point set", None))
        self.pushButton_Apllytopanel.setText(_translate("MainWindow", "Aplly to panel", None))
        self.label_3.setText(_translate("MainWindow", "Concrete", None))
        self.label_6.setText(_translate("MainWindow", "Steel", None))
        self.label_7.setText(_translate("MainWindow", "d [mm]", None))
        self.label_8.setText(_translate("MainWindow", "a [mm]", None))
        self.label_9.setText(_translate("MainWindow", "cracklim [mm]", None))
        self.label_4.setText(_translate("MainWindow", "Side p", None))
        self.label_5.setText(_translate("MainWindow", "Side n", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", ">>> Panel properties", None))
        self.pushButton_plot_nx.setText(_translate("MainWindow", "nx force", None))
        self.pushButton_plot_ny.setText(_translate("MainWindow", "ny force", None))
        self.pushButton_plot_nxy.setText(_translate("MainWindow", "nxy force", None))
        self.pushButton_plot_mx.setText(_translate("MainWindow", "mx momenet", None))
        self.pushButton_plot_my.setText(_translate("MainWindow", "my moment", None))
        self.pushButton_plot_mxy.setText(_translate("MainWindow", "mxy moment", None))
        self.pushButton_plot_equNX.setText(_translate("MainWindow", "equ_NX", None))
        self.pushButton_plot_equNY.setText(_translate("MainWindow", "equ_NY", None))
        self.pushButton_plot_equMX.setText(_translate("MainWindow", "equ_MX", None))
        self.pushButton_plot_equMY.setText(_translate("MainWindow", "equ_MY", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", ">>> Plot internal force", None))
        self.label_38.setText(_translate("MainWindow", "Side  p >>", None))
        self.label_39.setText(_translate("MainWindow", "Side n >>", None))
        self.label_10.setText(_translate("MainWindow", "Dir. x", None))
        self.label_11.setText(_translate("MainWindow", "Dir.y", None))
        self.pushButton_plotApx.setText(_translate("MainWindow", "Apx", None))
        self.pushButton_plotApy.setText(_translate("MainWindow", "Apy", None))
        self.pushButton_plotAnx.setText(_translate("MainWindow", "Anx", None))
        self.pushButton_plotAny.setText(_translate("MainWindow", "Any", None))
        self.pushButton_plot_crackx.setText(_translate("MainWindow", "crackx", None))
        self.pushButton_plot_cracky.setText(_translate("MainWindow", "cracky", None))
        self.pushButton_plot_ksieffx.setText(_translate("MainWindow", "ksieffx", None))
        self.pushButton_plot_ksieffy.setText(_translate("MainWindow", "ksieffy", None))
        self.pushButton_plot_mimosx.setText(_translate("MainWindow", "mimosx", None))
        self.pushButton_plot_mimosy.setText(_translate("MainWindow", "mimosy", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", ">>> Plot results", None))
        self.label_12.setText(_translate("MainWindow", "Side p", None))
        self.label_13.setText(_translate("MainWindow", "Side n", None))
        self.label_scaleUnit.setText(_translate("MainWindow", "TextLabel", None))
        self.label_scaleUnit_2.setText(_translate("MainWindow", "(per meter value)", None))
        self.label_14.setText(_translate("MainWindow", "Edit scale", None))
        self.pushButton_ApllyToScale.setText(_translate("MainWindow", "Aplly to scale", None))
        self.pushButton_spaceing.setText(_translate("MainWindow", "+spacing", None))
        self.label_2.setText(_translate("MainWindow", "Preset scale", None))
        self.pushButton_mapApx.setText(_translate("MainWindow", "Ax map", None))
        self.pushButton_mapApy.setText(_translate("MainWindow", "Ay map", None))
        self.pushButton_mapAnx.setText(_translate("MainWindow", "Ax map", None))
        self.pushButton_mapAny.setText(_translate("MainWindow", "Ay map", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("MainWindow", ">>> Reinforcement map", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("MainWindow", ">>> Raport", None))
        self.actionSave_projekt.setText(_translate("MainWindow", "Save projekt", None))
        self.actionOpen_projekt.setText(_translate("MainWindow", "Open projekt", None))

