notifications:
  email: false

language: c
sudo: false

env:
  global:
    - NUMPY_VERSION=1.9
  
matrix:
  fast_finish: true

  ### let osx fail for the time being, while I figure out the details
  allow_failures:
    os: osx
  
  include:
    #### osx with clang doesn't use openmp -> so they are the slowest. Run them first
    # - os: osx
    #   compiler: clang
    #   env: COMPILER=clang-3.6 V=3.6 PYTHON_VERSION=2.7
    #   before_install:
    #     - wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh
    #     - bash miniconda.sh -b -p $HOME/miniconda
    #     - export PATH="$HOME/miniconda/bin:$PATH"
    #     - conda create -q --yes -n test python=$PYTHON_VERSION
    #     - source activate test
    #     - conda install -q --yes numpy=$NUMPY_VERSION
    #     - brew update && brew install gsl 

    # - os: osx
    #   compiler: clang
    #   env: COMPILER=clang-3.6 V=3.6 PYTHON_VERSION=3.4
    #   before_install:
    #     - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    #     - bash miniconda.sh -b -p $HOME/miniconda
    #     - export PATH="$HOME/miniconda/bin:$PATH"
    #     - conda create -q --yes -n test python=$PYTHON_VERSION
    #     - source activate test
    #     - conda install -q --yes numpy=$NUMPY_VERSION 
    #     - brew update && brew install gsl

    # - os: osx
    #   osx_image: xcode7
    #   compiler: clang
    #   env: COMPILER=clang V='Apple LLVM 7.0.0' PYTHON_VERSION=3.5
    #   before_install:
    #     - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    #     - bash miniconda.sh -b -p $HOME/miniconda
    #     - export PATH="$HOME/miniconda/bin:$PATH"
    #     - conda create -q --yes -n test python=$PYTHON_VERSION
    #     - source activate test
    #     - conda install -q --yes numpy=$NUMPY_VERSION 
    #     - brew update && brew install gsl
                     
    - os: linux
      compiler: clang
      addons:
        apt: 
          sources: ['ubuntu-toolchain-r-test','llvm-toolchain-precise-3.6']
          packages: ['clang-3.6','libgsl0-dev']
      env: COMPILER=clang-3.6 V=3.6 PYTHON_VERSION=2.7 
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -q --yes -n test python=$PYTHON_VERSION
        - source activate test
        - conda install -q --yes numpy=$NUMPY_VERSION

    - os: linux
      compiler: clang
      addons:
        apt: 
          sources: ['ubuntu-toolchain-r-test','llvm-toolchain-precise-3.6']
          packages: ['clang-3.6','libgsl0-dev']
      env: COMPILER=clang-3.6 V=3.6 PYTHON_VERSION=3.5
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -q --yes -n test python=$PYTHON_VERSION
        - source activate test
        - conda install -q --yes numpy=$NUMPY_VERSION
        
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8','libgsl0-dev']
      env: COMPILER=gcc-4.8 PYTHON_VERSION=2.7
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -q --yes -n test python=$PYTHON_VERSION
        - source activate test
        - conda install -q --yes numpy=$NUMPY_VERSION

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8','libgsl0-dev']
      env: COMPILER=gcc-4.8 PYTHON_VERSION=3.5
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -q --yes -n test python=$PYTHON_VERSION
        - source activate test
        - conda install -q --yes numpy=$NUMPY_VERSION
        
    # - os: osx
    #   compiler: gcc
    #   env: COMPILER=gcc-4.8 PYTHON_VERSION=3.5 FAMILY=gcc V=4.8
    #   before_install:
    #     - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    #     - bash miniconda.sh -b -p $HOME/miniconda
    #     - export PATH="$HOME/miniconda/bin:$PATH"
    #     - conda create -q --yes -n test python=$PYTHON_VERSION
    #     - source activate test
    #     - conda install -q --yes numpy=$NUMPY_VERSION gcc=4.8
    #     - brew update && brew install gsl 

install:
  - make install CC=$COMPILER
  - python setup.py install
        
script:
  - make tests CC=$COMPILER
  
