# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='pulse_counter_rpc',
  serialized_pb=_b('\n\x0c\x63onfig.proto\x12\x11pulse_counter_rpc\"\x8b\x01\n\x06\x43onfig\x12\x15\n\rserial_number\x18\x01 \x01(\r\x12\x19\n\tbaud_rate\x18\x02 \x01(\r:\x06\x31\x31\x35\x32\x30\x30\x12\x13\n\x0bi2c_address\x18\x03 \x01(\r\x12\x1c\n\x11mux_channel_a_pin\x18\x04 \x01(\r:\x01\x34\x12\x1c\n\x11mux_channel_b_pin\x18\x05 \x01(\r:\x01\x38\"\x8f\x01\n\x05State\x12\x15\n\tpulse_pin\x18\x01 \x01(\x05:\x02-1\x12\x18\n\rpulse_channel\x18\x02 \x01(\r:\x01\x30\x12\x1a\n\x0fpulse_direction\x18\x03 \x01(\r:\x01\x33\x12!\n\x12pulse_count_enable\x18\x04 \x01(\x08:\x05\x66\x61lse\x12\x16\n\x0bpulse_count\x18\x05 \x01(\r:\x01\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='pulse_counter_rpc.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='pulse_counter_rpc.Config.serial_number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baud_rate', full_name='pulse_counter_rpc.Config.baud_rate', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=115200,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i2c_address', full_name='pulse_counter_rpc.Config.i2c_address', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mux_channel_a_pin', full_name='pulse_counter_rpc.Config.mux_channel_a_pin', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mux_channel_b_pin', full_name='pulse_counter_rpc.Config.mux_channel_b_pin', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=8,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=175,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='pulse_counter_rpc.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pulse_pin', full_name='pulse_counter_rpc.State.pulse_pin', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pulse_channel', full_name='pulse_counter_rpc.State.pulse_channel', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pulse_direction', full_name='pulse_counter_rpc.State.pulse_direction', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pulse_count_enable', full_name='pulse_counter_rpc.State.pulse_count_enable', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pulse_count', full_name='pulse_counter_rpc.State.pulse_count', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=321,
)

DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['State'] = _STATE

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
  DESCRIPTOR = _CONFIG,
  __module__ = 'config_pb2'
  # @@protoc_insertion_point(class_scope:pulse_counter_rpc.Config)
  ))
_sym_db.RegisterMessage(Config)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), dict(
  DESCRIPTOR = _STATE,
  __module__ = 'config_pb2'
  # @@protoc_insertion_point(class_scope:pulse_counter_rpc.State)
  ))
_sym_db.RegisterMessage(State)


# @@protoc_insertion_point(module_scope)
