---

title: Three stacks
source: Cracking The Coding Interview by Gayle Laakman
description: Use a single array to implement three stacks.
tests:
  - {input: 3 2 3 4 5 6 7\n2 5 6 7 8\n5 2 3 5 4 7 8 5, output: 2 3 4\n5 6\n2 3}
  - {input: 5 2 3\n3 2 5 4\n0 1, output: \n\n1}

---

title: Three stacks
source: Cracking The Coding Interview by Gayle Laakman
description: |
  Design a stack which, in addition to push and pop, also has a function min which returns the minimum element.
  Push, pop and min should all operate in O(1) time.
tests:
  - {input: 2 p 3 5 6 m 4 m p p 1 m, output: 3\n3\n1}
  - {input: 3 m 2 m p m, output: 3\n2\n3}
  - {input: m p, output: ""}

---

title: Set of Stacks
source: Cracking The Coding Interview by Gayle Laakman
description: |
  Imagine a (literal) stack of plates If the stack gets too high, it might topple.
  Therefore, in real life, we would likely start a new stack when the previous stack exceeds some threshold.
  Implement a data structure SetOfStacks that mimics this. SetOfStacks should be composed of several stacks,
  and should create a new stack once the previous one exceeds capacity. SetOfStacks push() and SetOfStacks
  pop() should behave identically to a single stack (that is, pop() should return the same values as it would
  if there were just a single stack). Implement a function popAt(int index) which performs a pop operation on
  a specific sub-stack.
tests:
  - {input: 1 2 3 4 5 6 p 7 8 9 p p, output: 1 2 3 4 5 7}
  - {input: 1 2 3 4 5 6 p 7 8 9 p1 p1, output: 1 2 3 7 8 9}
  - {input: 1 2 3 4 5 p2, output: 1 2 3 4 5}

---

title: Towers of Hanoi
source: Cracking The Coding Interview by Gayle Laakman
description: |
  In the classic problem of the Towers of Hanoi, you have 3 rods and N disks of different sizes which can slide onto any
  tower. The puzzle starts with disks sorted in ascending order of size from top to bottom (e.g., each disk sits on top
  of an even larger one). You have the following constraints:

  (A) Only one disk can be moved at a time
  (B) A disk is slid o  the top of one rod onto the next rod
  (C) A disk can only be placed on top of a larger disk

  Write a program to move the disks from the first rod to the last using Stacks.

  Input: Number of rings
  Output: Succesfull?
tests:
  - {input: 1, output: 1}
  - {input: 2, output: 1}
  - {input: 3, output: 1}
  - {input: 6, output: 1}

---

title: Queue as two stacks
source: Cracking The Coding Interview by Gayle Laakman
description: Implement a queue using two stacks.
tests:
  - {input: 2 3 d 4 9 5 d d 7 6 5, output: 2\n3\n4}
  - {input: 2 d d, output: 2}
  - {input: 3 4 5, output: 3 4 5}
  - {input: "", output: ""}

---

title: Sort stack
source: Cracking The Coding Interview by Gayle Laakman
description: |
  Write a program to sort a stack in ascending order.
  You should not make any assumptions about how the stack is implemented.
  The following are the only functions that should be used to write this program: push | pop | peek | isEmpty
tests:
  - {input: 6 7 5 4 2 9, output: 2 4 5 6 7 9}
  - {input: 1 2 1 2 1, output: 1 1 1 2 2}
  - {input: 1, output: 1}
  - {input: "", output: ""}

---

title: Middle of stack
source: https://github.com/kylesteiner/coding-challenges
description: Find the element in the middle position of a stack. Optimize for space.

...