language: python
python: 3.5
sudo: false
branches:
    only:
        - master
        - /^\d\.\d+$/

env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py35

addons:
    apt:
        packages:
            - python-numpy
            - python-scipy
            - libatlas-base-dev
            - liblapack-dev
            - gfortran

install:
    - pip install -U pip tox codecov

script: tox

after_success:
    - codecov

cache:
    directories:
        - $HOME/.cache/pip
