# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tellafriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254, verbose_name='Sender e-mail')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Friend e-mail')),
                ('message', models.TextField(blank=True, default=b'', verbose_name='Message from you')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sending date')),
                ('user_agent', models.CharField(max_length=255, verbose_name='User agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
            },
        ),
    ]
