# Un nouveau plan
- plan:
    # Le nom du plan
    name: kernel.modprobe.dummy
    # Une description
    description: Ajout du module dummy si il n'existe pas
    # Les différentes taches à executer
    # (ici 1: 2: indique une sequentialité :
    # attendre la fin de la tache pour lancer la suivante)
    steps:
      1: kernel.modprobe.remove
      2: kernel.modprobe.add
    # La tache de fin, qui se doit de retourner un booléan "true" si tout est oki
    assert:
      1: kernel.modprobe.check

    args:
      - dummy
    kwargs:
      - numdummies: 2

- plan:
    name: kernel.modprobe.bridge
    step:
      - kernel.modprobe.add
    assert:
      - kernel.modprobe.check
    args:
      - bridge