
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "948a7310e0363869953fe7233beff720f0f4bf12",
 "version": "0.2.post43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
