# This file was auto-generated by salt's setup on Wednesday, 27 January 2016 @ 23:01:26 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2015, 8, 4, 0, 0, 0, None)
