__version__ = "0.1.post5"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = 'develop'
__git_remote_tracking_branch__ = 'origin/develop'
__git_remote_url__ = 'git@github.com:wiggin15/pypi_rankings.git'
__git_head_hash__ = 'afa6fd9c2b38caac4d86be100ba6ed54e42b8761'
__git_head_subject__ = 'disable requests warnings'
__git_head_message__ = ''
__git_dirty_diff__ = ''
__git_commit_date__ = '2016-01-29 16:06:47'
