
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3bb622828d96048b8b63e84a6b07398ef0aed8db",
 "version": "2016.0131.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
