
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f55d168d958e26c39c65783f5c604993c70e997e",
 "version": "1.0.0.post.dev70"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
