cmdargs:
  verbose: no
  severity: warning
  error-limit: 50
  stat: no
  color: no
  json: no
  env:
    neovim: no

policies:
  ProhibitImplicitScopeVariable:
    suppress_autoload: no

  # Experimental
  ProhibitUnusedVariable:
    enabled: no
