web:
  build: .
  ports:
   - "5000:5000"
  volumes:
   - .:/code
  links:
   - redis
   - postgresql
   - memcached
redis:
  image: redis
postgresql:
  image: postgresql
memcached:
  image: memcached