language: python
python:
  - 2.7
  - 3.5
sudo: false
env:
  - DJANGO_VERSION=1.7.10
  - DJANGO_VERSION=1.8.9
  - DJANGO_VERSION=1.9.2
matrix:
  allow_failures:
    - python: 3.5
before_install:
  - if [ $TRAVIS_PYTHON_VERSION == 3.5 ]; then sed -ie "s/^robotframework$/robotframework-python3/g" requirements.txt; fi
install:
  - cat requirements.txt
  - pip install -r requirements.txt
  - pip install -q flake8
  - pip install -q  --pre Django==$DJANGO_VERSION
  - python setup.py install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - flake8 .
  - pybot DjangoLibrary/tests/
after_script:
  - firefox --version
