cmdargs:
  verbose: no
  severity: warning
  error-limit: 50

policies:
  ProhibitImplicitScopeVariable:
    enabled: yes
    suppress_autoload: no

  # Experimental
  ProhibitUnusedVariable:
    enabled: no
