
# This file was generated by 'versioneer.py' (0.13+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.1'
version_full = '746eb19335d7f32c0132ed9a0ff6a3288dee1cc0'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

