heat_template_version: 2013-05-23

description: >
  Heat HelloWorld template to describe basic usage of Heat.
  HelloWorld starts $number of VM instances.
  - $key_name is required to enable SSH access.

parameters:

  key_name:
    type: string
    description : Name of a KeyPair to enable SSH access to the instance
  cluster_size:
    type: number
    label: Cluster size
    description: Number of instances in cluster.
    default: 3
  instance_type:
    type: string
    description: Instance type for server
    default: m1.small
    constraints:
      - allowed_values: [m1.small, m1.medium, m1.large, m1.xlarge]
        description: instance_type must be one of m1.small, m1.medium,  m1.large, or m1.xlarge
  image_id:
    type: string
    description: >
      Name or ID of the image to use for the HelloWorld server.
      Recommended values are futuresystems/ubuntu-14.04 on Juno and
      Ubuntu-14.04-64 on Kilo
    default: futuresystems/ubuntu-14.04

resources:
  scaling:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: cluster_size }
      resource_def:
        type: OS::Nova::Server
        properties:
          image: { get_param: image_id }
          flavor: { get_param: instance_type }
          key_name: { get_param: key_name }
          user_data: |
            #!/bin/bash -v

            echo hello world
