
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3a25f234022bf7c064707326887791c5a9444799",
 "version": "v0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
