
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b67166b583793a7c2cb4737039525e55d456d82d",
 "version": "2.10.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
