site_name: Django import data
repo_url: https://github.com/lev-veshnyakov/django-import-data
site_author: Lev Veshnyakov
theme: readthedocs
docs_dir: docs
dev_addr: 0.0.0.0:80
pages:
  - 'Home': index.md
