
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d6fff701f052317be3b20ac70de35116d56a6c44",
 "version": "0.3.post28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
