sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  include:
    - python: "2.6"  # these are just to make travis's UI a bit prettier
      env: TOXENV=py26-threads
    - python: "2.6"
      env: TOXENV=py26-greenlets
    - python: "2.7"
      env: TOXENV=py27-threads
    - python: "2.7"
      env: TOXENV=py27-greenlets
    - python: "3.3"
      env: TOXENV=py33-threads
    - python: "3.3"
      env: TOXENV=py33-greenlets
    - python: "3.4"
      env: TOXENV=py34-threads
    - python: "3.4"
      env: TOXENV=py34-greenlets
    - python: "3.5"
      env: TOXENV=py35-threads
    - python: "3.5"
      env: TOXENV=py35-greenlets
    - python: "3.5"
      env: TOXENV=py35-nocolorama
    - python: "pypy"
      env: TOXENV=pypy-threads
    - python: "pypy"
      env: TOXENV=pypy-greenlets


    # Meta
    - python: "3.5"
      env: TOXENV=flake8
    - python: "2.7"
      env: TOXENV=manifest
    - python: "2.7"
      env: TOXENV=docs
    - python: "3.5"
      env: TOXENV=readme

install:
  - pip install tox

script:
  - tox

before_install:
  - pip install codecov

after_success:
  - tox -e coverage-report
  - codecov
