
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e9e975312eaa1d7ed31f0fca8a72bc1f2e72ecbe",
 "version": "2.10.39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
