
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "29d15d14aa6d690a8afc10fa85e081f0ff284f11",
 "version": "0.1.97"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
