
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c5e585ed496f3132ebb668559df119563aafb592",
 "version": "1.0.0.post.dev66"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
