
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.18'
version_full = 'a66d72fd41afaeef2d1dc8b3250c746c9fc2ffa8'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

