
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "24935bf2c4b3bd046a41d8120cdf20b08f1f9329",
 "version": "1.0.0.post.dev64"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
