# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=40)),
                ('color', models.CharField(choices=[(b'#f56954', b'Danger'), (b'#f39c12', b'Warning'), (b'#00a65a', b'Success'), (b'#00c0ef', b'Info'), (b'#3c8dbc', b'Primary'), (b'#d2d6de', b'Gray'), (b'#111111', b'Black')], default=b'#111111', max_length=7)),
                ('content', models.TextField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('seen_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('send_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name=b'user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
