
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "85c35190e5088663bdaf59e2bcb8d3dfd1cb083f",
 "version": "2.10.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
