
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8600ea912ff2c6f3303b7036738f0fa3097958bd",
 "version": "2.10.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
