language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
install:
  - python setup.py install
  - pip install coverage
script:
  - nosetests -v --with-coverage --cover-tests --cover-package=noseselecttests noseselecttests/tests.py
