
/* #########################################################################
 * [2016-01-12 15:46:18.468000] THIS FILE IS AUTOGENERATED - DO NOT EDIT!
 * ######################################################################### */

#ifndef ___DROPBOT_DX___
#define ___DROPBOT_DX___

#include "DropbotDx/Properties.h"
#include "DropbotDx/CommandProcessor.h"

#endif  // #ifndef ___DROPBOT_DX___

