language: python
python:
- '2.7'
- '3.4'
before_install:
- pip install codecov
install:
- pip install .
script:
- coverage run tests/all_tests.py
after_success:
- coverage combine
- codecov
deploy:
  provider: pypi
  user: travis.rrze-hpc
  password:
    secure: G6JtvRrGWSYi55kplvN0Gc/tnuCTXL87lhUTAMJZtAOGcMxW50H5ar0/6rJv3zCLblx3WzBWQBZO6zkOiObC+bwdhdeWZYT69XAK4gL2rsYqGIh8BwVL2RmwCkTSC95/kpGdhahd4wa3fmE5G7we+u+QGS5ETU0IJyY6ujDIDQEOW4A/Q4d5jq0I5tU618htU9AzIMGA0SJUdBquH0suvApsFSvgCGSpp1uPlFc5kAvhOjTNo74KPLrh7xhFgGKEvo8Apcb9akseFmBl3prluCDQFwtEP7nifWEw69PkLwrMWzG1LYdIndXWj/UIuVHi/IaJbew7R93nLqCEyQphpFJ4e4ZEw99lO+FIzmGK1SERyyEbf+M89R8RW/LG2uKpN1e1Ov/gF4X/wl8DDRv4Dp00mBtM0gGxUDUCJnCZ8XvLaCyghfvZj/C4VOn8idW0ToOO6EY9cY+GHOZS8yRFj3JONL47KLIuS5tMRUPZ7PnJ0Os+u2kR4W+ucFj22ycv2aQ4wghOfDxFwetJlvVtOV9oPjYiQBcpuAIIZ5xSIbU9W55eOTUhNG6Q0+HDrFsEyWONXRv6wJgLbgDLv4aZ6COJBcvJHynchE62TlMuElVU2hXt75rQPdb5gGN+T2oO7jX1FQW4B4nDVuTbDbjm8XKApSq/1nAa5u83IkUS/I4=
  on:
    repo: RRZE-HPC/pycachesim