
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1048efd6a204728e5967591751b1d21576e5a0bb",
 "version": "2016.0210.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
