# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper_label', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperRunLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='scraperrun',
            name='logs',
            field=models.ManyToManyField(to='okscraper_django.ScraperRunLog'),
        ),
    ]
