# This file was auto-generated by salt's setup on Wednesday, 17 February 2016 @ 04:02:04 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2015, 8, 7, 0, 0, 0, None)
