
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b3702a3c937057de0f395ba59f1fd90acdffb287",
 "version": "1.0.0.post.dev52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
