heat_template_version: 2013-05-23

description: Hadoop cluster with OpenStack Heat

parameters:
  KeyName:
    type: string
    description: Key name for logging in to instance
  PublicKeyString:
    type: string
    description: a public key string
  PrivateKeyString:
    type: string
    description: a private key string
  UserName:
    type: string
    description: User name
    default: ""

resources:
  security_group:
    type: AWS::EC2::SecurityGroup
    properties:
      GroupDescription: "SSH(22)"
      SecurityGroupIngress:
      - IpProtocol: "tcp"
        FromPort: "22"
        ToPort : "22"
        CidrIp : "0.0.0.0/0"
  floatingip:
    type: OS::Nova::FloatingIP
    properties:
      pool: ext-net

  hc-slave1:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: KeyName }
      image: "futuresystems/hadoop-v2"
      flavor: "m1.small"
      name: 
        list_join: [ "-", [ { get_param : UserName }, "hc-slave1" ] ]
      security_groups:
        - "default"
        - { get_resource: security_group }
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo $publickey >> /root/.ssh/authorized_keys
            echo "$privatekey" > /root/.ssh/id_rsa
            chmod 600 /root/.ssh/id_rsa

            echo "hc-slave1" > /etc/hostname
            hostname hc-slave1

          params:
            $publickey: { get_param: PublicKeyString }
            $privatekey: { get_param: PrivateKeyString }
  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floatingip }
      server_id: { get_resource: 'hc-slave1' }

  hc-slave2:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: KeyName }
      image: "futuresystems/hadoop-v2"
      flavor: "m1.small"
      name: 
        list_join: [ "-", [ { get_param : UserName }, "hc-slave2" ] ]
      security_groups:
        - "default"
        - { get_resource: security_group }
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo $publickey >> /root/.ssh/authorized_keys
            echo "$privatekey" > /root/.ssh/id_rsa
            chmod 600 /root/.ssh/id_rsa

            echo "hc-slave2" > /etc/hostname
            hostname hc-slave2

          params:
            $publickey: { get_param: PublicKeyString }
            $privatekey: { get_param: PrivateKeyString }
  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floatingip }
      server_id: { get_resource: 'hc-slave2' }

  hc-slave3:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: KeyName }
      image: "futuresystems/hadoop-v2"
      flavor: "m1.small"
      name: 
        list_join: [ "-", [ { get_param : UserName }, "hc-slave3" ] ]
      security_groups:
        - "default"
        - { get_resource: security_group }
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo $publickey >> /root/.ssh/authorized_keys
            echo "$privatekey" > /root/.ssh/id_rsa
            chmod 600 /root/.ssh/id_rsa

            echo "hc-slave3" > /etc/hostname
            hostname hc-slave3

          params:
            $publickey: { get_param: PublicKeyString }
            $privatekey: { get_param: PrivateKeyString }
  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floatingip }
      server_id: { get_resource: 'hc-slave3' }

  hc-master:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: KeyName }
      image: "futuresystems/hadoop-v2"
      flavor: "m1.small"
      name: 
        list_join: [ "-", [ { get_param : UserName }, "hc-master" ] ]
      security_groups:
        - "default"
        - { get_resource: security_group }
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo $publickey >> /root/.ssh/authorized_keys
            echo "$privatekey" > /root/.ssh/id_rsa
            chmod 600 /root/.ssh/id_rsa

            echo "hc-master" > /etc/hostname
            hostname hc-master

            cat <<EOF > ~/hadoop/etc/hadoop/slaves
            hc-slave1
            hc-slave2
            hc-slave3
            EOF
            
            hcmaster=$(ifconfig eth0 | awk -F':' '/inet addr/{split($2,_," ");print _[1]}')

            cat << EOF > /etc/hosts.hadoop
            
            # internal network addresses for hadoop cluster
            $hcmaster hc-master
            $hc-slave1 hc-slave1
            $hc-slave2 hc-slave2
            $hc-slave3 hc-slave3
            EOF

            cat /etc/hosts.hadoop >> /etc/hosts

            scp -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no /etc/hosts.hadoop $hc-slave1:/etc/hosts.hadoop
            scp -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no /etc/hosts.hadoop $hc-slave2:/etc/hosts.hadoop
            scp -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no /etc/hosts.hadoop $hc-slave3:/etc/hosts.hadoop
            ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $hc-slave1 "cat /etc/hosts.hadoop >> /etc/hosts"
            ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $hc-slave2 "cat /etc/hosts.hadoop >> /etc/hosts"
            ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $hc-slave3 "cat /etc/hosts.hadoop >> /etc/hosts"

            for slave in `cat ~/hadoop/etc/hadoop/slaves`
            do
               ssh-keyscan $slave >> ~/.ssh/known_hosts
               for i in `seq 1 12`
               do
                  ssh $slave ls ~/hadoop/etc/hadoop &> /dev/null
                  IS_INSTALLED=$?
                  if [ 0 -eq "$IS_INSTALLED" ]
                  then
                     ssh $slave "ssh-keyscan hc-master >> ~/.ssh/known_hosts"
                     ssh $slave "ssh-keyscan hc-slave1 >> ~/.ssh/known_hosts"
                     ssh $slave "ssh-keyscan hc-slave2 >> ~/.ssh/known_hosts"
                     ssh $slave "ssh-keyscan hc-slave3 >> ~/.ssh/known_hosts"
                     break
                  fi
                  sleep 5
                  echo waiting.
               done
               rsync -avxP --exclude=logs ~/hadoop/etc/hadoop/ $slave:~/hadoop/etc/hadoop/
            done

            ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $hcmaster "source ~/.hadooprc;hdfs namenode -format"
            ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $hcmaster "source ~/.hadooprc;hadoop/sbin/hadoop-daemon.sh --script hdfs start namenode"
            ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $hcmaster "source ~/.hadooprc;hadoop/sbin/yarn-daemon.sh start resourcemanager"

            ssh -q $hc-slave1 "source ~/.hadooprc;hadoop/sbin/hadoop-daemon.sh --script hdfs start datanode"
            ssh -q $hc-slave1 "source ~/.hadooprc;hadoop/sbin/yarn-daemon.sh start nodemanager"

            ssh -q $hc-slave2 "source ~/.hadooprc;hadoop/sbin/hadoop-daemon.sh --script hdfs start datanode"
            ssh -q $hc-slave2 "source ~/.hadooprc;hadoop/sbin/yarn-daemon.sh start nodemanager"

            ssh -q $hc-slave3 "source ~/.hadooprc;hadoop/sbin/hadoop-daemon.sh --script hdfs start datanode"
            ssh -q $hc-slave3 "source ~/.hadooprc;hadoop/sbin/yarn-daemon.sh start nodemanager"

          params:
            $hc-slave1: { get_attr: [ hc-slave1, first_address ] }
            $hc-slave2: { get_attr: [ hc-slave2, first_address ] }
            $hc-slave3: { get_attr: [ hc-slave3, first_address ] }
            $publickey: { get_param: PublicKeyString }
            $privatekey: { get_param: PrivateKeyString }

  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floatingip }
      server_id: { get_resource: 'hc-master' }

