# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edocuments/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(583, 525)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.search = QtWidgets.QWidget()
        self.search.setObjectName("search")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.search)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_text = QtWidgets.QLineEdit(self.search)
        self.search_text.setObjectName("search_text")
        self.horizontalLayout.addWidget(self.search_text)
        self.search_btn = QtWidgets.QPushButton(self.search)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.search)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.advance_query = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.advance_query.setObjectName("advance_query")
        self.verticalLayout_7.addWidget(self.advance_query)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search_result_list = QtWidgets.QListWidget(self.search)
        self.search_result_list.setObjectName("search_result_list")
        self.horizontalLayout_2.addWidget(self.search_result_list)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.search_result_test = QtWidgets.QTextBrowser(self.search)
        self.search_result_test.setObjectName("search_result_test")
        self.verticalLayout_5.addWidget(self.search_result_test)
        self.search_result_graphics = QtWidgets.QGraphicsView(self.search)
        self.search_result_graphics.setObjectName("search_result_graphics")
        self.verticalLayout_5.addWidget(self.search_result_graphics)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.search, "")
        self.scan = QtWidgets.QWidget()
        self.scan.setObjectName("scan")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scan)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.scan)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.scan_type = QtWidgets.QComboBox(self.scan)
        self.scan_type.setObjectName("scan_type")
        self.horizontalLayout_3.addWidget(self.scan_type)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.direct = QtWidgets.QGroupBox(self.scan)
        self.direct.setObjectName("direct")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.direct)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scan_to = QtWidgets.QLineEdit(self.direct)
        self.scan_to.setObjectName("scan_to")
        self.horizontalLayout_5.addWidget(self.scan_to)
        self.scan_browse = QtWidgets.QPushButton(self.direct)
        self.scan_browse.setObjectName("scan_browse")
        self.horizontalLayout_5.addWidget(self.scan_browse)
        self.scan_start = QtWidgets.QPushButton(self.direct)
        self.scan_start.setObjectName("scan_start")
        self.horizontalLayout_5.addWidget(self.scan_start)
        self.verticalLayout_2.addWidget(self.direct)
        self.groupBox = QtWidgets.QGroupBox(self.scan)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scan_comments = QtWidgets.QLabel(self.groupBox)
        self.scan_comments.setText("")
        self.scan_comments.setObjectName("scan_comments")
        self.verticalLayout_6.addWidget(self.scan_comments)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.scan, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 583, 24))
        self.menubar.setObjectName("menubar")
        self.menuUpdate_library = QtWidgets.QMenu(self.menubar)
        self.menuUpdate_library.setObjectName("menuUpdate_library")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.menuUpdate_library.addAction(self.actionUpdate)
        self.menubar.addAction(self.menuUpdate_library.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "eDocuments - a Simple and Productive Personal Documents Library"))
        self.search_btn.setText(_translate("MainWindow", "Search"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Advance query"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.search), _translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Scan type"))
        self.direct.setTitle(_translate("MainWindow", "Scan"))
        self.scan_browse.setText(_translate("MainWindow", "Browse..."))
        self.scan_start.setText(_translate("MainWindow", "Scan"))
        self.groupBox.setTitle(_translate("MainWindow", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scan), _translate("MainWindow", "Scan"))
        self.menuUpdate_library.setTitle(_translate("MainWindow", "&Library"))
        self.actionUpdate.setText(_translate("MainWindow", "&Update"))

