
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a0f5ff083cdda8768a5bb0cfe66d84e082d54829",
 "version": "0.1.60"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
