
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ccac5e4d83d86fd484c0c7b48fe3682ca3807e3b",
 "version": "1.0.0.post.dev84"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
