
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.16'
version_full = '82c7d4a1174170f58a24f1321ab5562688fe998f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

