
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6'
version_full = '10d462de26f39ada63fac55ed35ef83242e09267'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

