
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "08ee8d3211810ee4ed202be615a0e043e2e9a19a",
 "version": "1.0.0.rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
