
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e19be84aff6b2824444b7fffab917481759d9c0c",
 "version": "0.2.post28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
