
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0b9eafd6495bf0045d13f6d720040644fde6b9a3",
 "version": "0.1.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
