
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "68d1dfbc839cffe38a2b3b6836383a84e41fb62a",
 "version": "0.1.43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
