
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2'
version_full = 'f332f8107f9478f3984bacf0169a92c1675a6222'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

