
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5133eafdeb9e85fb809ba1856957c0a42400e1a7",
 "version": "2.10.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
