
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f7c1ad7b5bd58d16f473fc7074791d6f62931020",
 "version": "1.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
