
# This file was generated by 'versioneer.py' (0.11) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.0'
version_full = '43fcf196eeea42c70df2130dbdccf173b0b9eb04'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

