heat_template_version: 2014-10-16
description: 'No-op task'

parameters:
  servers:
    type: json
  input_values:
    type: json
    default: {}
    description: input values for the software deployments
