sudo: false
language: python

matrix:
    include:
        - env: TOXENV=pep8
        - env: TOXENV=py3pep8
        - python: 2.7
          env: TOXENV=py27
        - python: 3.3
          env: TOXENV=py33
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: nightly
          env: TOXENV=py36
        - python: pypy
          env: TOXENV=pypy

install:
  - pip install tox
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls
