
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "837e7d526e22599d2dc357bc76804e9d004895b2",
 "version": "0.9.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
