
# This file was generated by 'versioneer.py' (1.1) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.4'
version_full = 'de0c230e242517442b8a6d98512eaa15386b7ce5'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

