
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "59e7e8391c0d406c11c21649d4e4c3596401a4d1",
 "version": "0.3.post23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
