# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2015-12-24 14:08:27.005773
from __future__ import unicode_literals
import datetime

version = "1.1.1"
githash = "fedd7c52ba80e2246f83b8d1752baa3a153a33e2"


major = 1
minor = 1
bugfix = 1

release = True
timestamp = datetime.datetime(2015, 12, 24, 14, 8, 27, 5773)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
