
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.3.1'
version_full = '6942d24587efc5d72a53fcc8e9153fb66fb6ab31'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

