---
install_dir: "~/Library/Application Support/osxstrap"
requirements:
  - src: jeremyltn.homebrew
  - src: jeremyltn.dotfiles
  - src: jeremyltn.git-repos
  - src: jeremyltn.osx-computername
  - src: jeremyltn.osx-oh-my-zsh
  - src: jeremyltn.osx-php
  - src: jeremyltn.osx-sudoers
  - src: jeremyltn.remote-vars
  - src: https://github.com/osxstrap/ansible-gitconfig.git
    name: jeremyltn.gitconfig
  - src: https://github.com/osxstrap/ansible-osx-defaults.git
    name: jeremyltn.osx-defaults
playbooks:
  - role: jeremyltn.remote-vars
    dev_role: ansible-remote-vars
    file: remote-vars
  - role: jeremyltn.osx-sudoers
    dev_role: ansible-osx-sudoers
    file: sudoers
  - role: jeremyltn.osx-computername
    dev_role: ansible.osx-computername
    file: computername
  - role: jeremyltn.homebrew
    dev_role: ansible-homebrew
    file: homebrew
  - role: jeremyltn.osx-php
    dev_role: ansible.osx-php
    file: php
  - role: jeremyltn.osx-oh-my-zsh
    dev_role: ansible-osx-oh-my-zsh
    file: oh-my-zsh
  - role: jeremyltn.dotfiles
    dev_role: ansible-dotfiles
    file: dotfiles
  - role: jeremyltn.gitconfig
    dev_role: ansible-gitconfig
    file: git-config
  - role: jeremyltn.git-repos
    dev_role: ansible-git-repos
    file: git-repos