
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "88dfc030db2d2457e29c6bc541e8d1e429671990",
 "version": "2.10.38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
