# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class GetDevicesResponseDevice(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        GetDevicesResponseDevice - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'name': 'str',
            'login_timeout': 'str',
            'public_key': 'str',
            'state': 'str'
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'login_timeout': 'loginTimeout',
            'public_key': 'publicKey',
            'state': 'state'
        }

        self._id = None
        self._name = None
        self._login_timeout = None
        self._public_key = None
        self._state = None

    @property
    def id(self):
        """
        Gets the id of this GetDevicesResponseDevice.


        :return: The id of this GetDevicesResponseDevice.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this GetDevicesResponseDevice.


        :param id: The id of this GetDevicesResponseDevice.
        :type: str
        """
        self._id = id

    @property
    def name(self):
        """
        Gets the name of this GetDevicesResponseDevice.


        :return: The name of this GetDevicesResponseDevice.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this GetDevicesResponseDevice.


        :param name: The name of this GetDevicesResponseDevice.
        :type: str
        """
        self._name = name

    @property
    def login_timeout(self):
        """
        Gets the login_timeout of this GetDevicesResponseDevice.


        :return: The login_timeout of this GetDevicesResponseDevice.
        :rtype: str
        """
        return self._login_timeout

    @login_timeout.setter
    def login_timeout(self, login_timeout):
        """
        Sets the login_timeout of this GetDevicesResponseDevice.


        :param login_timeout: The login_timeout of this GetDevicesResponseDevice.
        :type: str
        """
        self._login_timeout = login_timeout

    @property
    def public_key(self):
        """
        Gets the public_key of this GetDevicesResponseDevice.


        :return: The public_key of this GetDevicesResponseDevice.
        :rtype: str
        """
        return self._public_key

    @public_key.setter
    def public_key(self, public_key):
        """
        Sets the public_key of this GetDevicesResponseDevice.


        :param public_key: The public_key of this GetDevicesResponseDevice.
        :type: str
        """
        self._public_key = public_key

    @property
    def state(self):
        """
        Gets the state of this GetDevicesResponseDevice.


        :return: The state of this GetDevicesResponseDevice.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this GetDevicesResponseDevice.


        :param state: The state of this GetDevicesResponseDevice.
        :type: str
        """
        self._state = state

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other): 
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """ 
        Returns true if both objects are not equal
        """
        return not self == other

