# This file was auto-generated by zetup
#
# https://bitbucket.org/userzimmermann/zetup.py


from __future__ import absolute_import

import sys
import os
from collections import OrderedDict

from zetup.version import Version
from zetup.dist import Distribution
from zetup.requires import Requirements
from zetup.extras import Extras
from zetup.package import Packages, Package
from zetup.notebook import Notebook



zfg = sys.modules[__name__]

NAME = 'zcons'

EXTRAS = Extras([

], zfg=zfg)

NO_MAKE = []

VERSION = Version('0.1rc0')

URL = 'https://github.com/zimmermanncode/zcons'

TITLE = 'zcons'

MODULES = []

SETUP_HOOKS = []

DISTRIBUTION = Distribution(zfg)

DESCRIPTION = "Zimmermann's SCons wrapper"

CLASSIFIERS = ['Development Status :: 3 - Alpha', 'Intended Audience :: Developers', 'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)', 'Operating System :: OS Independent', 'Topic :: Software Development', 'Topic :: Utilities', 'Programming Language :: Python', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3.3', 'Programming Language :: Python :: 3.4', 'Programming Language :: Python :: 3.5']

KEEP_MADE = ['setup.py']

FORCE_MAKE = True

KEYWORDS = ['zetup', 'setup', 'scons', 'sconstruct', 'sconscript', 'install', 'installer', 'installation', 'build', 'builder', 'construct', 'construction', 'compile', 'compiler', 'compilation', 'zimmermann', 'zimmermanncode', 'userzimmermann', 'python3', 'python3']

PYTHON = ['2.7', '3.3', '3.4', '3.5']

SETUP_REQUIRES = None

SETUP_KEYWORDS = None

EMAIL = 'zimmermann.code@gmail.com'

PACKAGES = Packages([

Package('zcons',
  sources=[
    'error.py',
    'script.py',
    '__init__.py',
    '__main__.py'
    ],
  subpackages=[
    
    ],
  )

  ], root=os.path.dirname(os.path.dirname(os.path.realpath(__file__))))

REQUIRES = Requirements("""
zetup >= 0.2.30

""", zfg=zfg)

LICENSE = 'LGPLv3'

SCRIPTS = {'zcons': 'zcons.script:run'}

AUTHOR = 'Stefan Zimmermann'

TEST_COMMANDS = ['py.test -v test']