
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "68de17ce5b6d525c0fc4b1f791bad59b48604d0f",
 "version": "1.0.0.post.dev85"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
