
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.8'
version_full = '0d10affda39ccbb37860f32cdd7b7274742b52cb'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

