sudo: false
language: python
python: 
    - 2.7

env:
    - TOX_ENV=py27
    - TOX_ENV=py34

matrix:
    fast_finish: true

install:
    - pip install --upgrade pip 
    - pip install coveralls
    - pip install -r requirements.txt
    - python setup.py install

script:
    - tox -v -v -e $TOX_ENV

after_success:
    coveralls

after_failure:
    - for X in .tox/$TOX_ENV/log/*; do echo "$X\n"; cat "$X"; echo "\n\n"; done

