
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.23.0'
version_full = '94ec3ac4d531b170c4c2ebf80375849606e3efcb'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

