language: python
python:
  #  - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
virtualenv:
  system_site_packages: true
before_install:
    - sudo apt-get install -qq $(< apt_requirements.txt)
    - wget http://147.228.240.61/queetech/sample-extra-data/io3d_sample_data.zip && unzip io3d_sample_data.zip
# command to install dependencies
install:
    - "easy_install SimpleITK"
    - "pip install ."
    - "pip install -r requirements.txt"
# command to run tests
script: nosetests --with-coverage --cover-package=io3d
after_success:
    - coveralls
