
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5585768452100709b34ac75c686558f16455e549",
 "version": "2016.0203.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
