
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "13605a087ae4725d849e01739d63864f27e9da5b",
 "version": "2.10.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
