
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f52dc6b3d5f557d06e27e57c3f7740e4b1a64313",
 "version": "1.0.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
