
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bf49d417f2f3851e01375291993cb242f90e039e",
 "version": "2.10.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
