# Docker Infrastructure (see http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/ )
sudo: false

language: python
python:
  - "2.7"
install:
  - pip install pep8
script:
  - pep8 --ignore=E731 -v jiracli
