language: python
python:
  - "2.6"
  - "2.7"
env:
#  - DJANGO=1.3.1 DB=sqlite
  - DJANGO=1.4 DB=sqlite
install:
  
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r travis-requirements.txt --use-mirrors
script:
  - ./runtests.sh
