
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9d53f6ecd5e58b49469c4e76d7be9241a7e16396",
 "version": "0.1.58"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
