
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.0'
version_full = 'be3a952d229cbf135a9d49969c31f5c5d35503a0'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

