
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5c4b78ef9f68a0737f15bd606763df2507cdfd43",
 "version": "0.1.76"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
