
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "635c4d4372609002f62c4b9b541e14f228340ff4",
 "version": "0.2.post22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
