
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a0afb08fde42d1d26827e13197ad7bb58f7df8bf",
 "version": "1.0.0.rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
