
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "807668405e9832e5f5e9217bf70aab724f556652",
 "version": "16.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
