
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "fd1eb723e779e8033e89153a16ac1bfd45ca486d",
 "version": "0.9.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
