language: python
python:
  - 2.7
  - 3.4
before_install:
  - nvm install 4.0
  - npm install -g node-sass postcss-cli autoprefixer
  - npm install -g browserify babelify babel-preset-es2015
install:
  - pip install -e .[test]
script:
  - py.test
