
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.2'
version_full = '06b033e2b30c2d516063055fd7b6f8ab19ab3260'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

